# Generated by Django 4.2.1 on 2023-05-09 04:13

from django.db import migrations
import user.models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_student_project_group"),
    ]

    operations = [
        migrations.CreateModel(
            name="Faculty",
            fields=[],
            options={
                "verbose_name": "Faculty",
                "verbose_name_plural": "Faculties",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("user.user",),
            managers=[
                ("objects", user.models.UserManager()),
            ],
        ),
    ]
