# Generated by Django 4.2.1 on 2023-05-08 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0002_initial"),
        ("user", "0002_student_project_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="department",
            field=models.CharField(
                choices=[
                    ("information_technology", "Information Technology"),
                    ("computer_science", "Computer Science"),
                    ("electronics", "Electronics and Telecommunication"),
                    ("electrical", "Electrical"),
                    ("mechanical", "Mechanical"),
                    ("civil", "Civil"),
                ],
                verbose_name="department",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="enrolment_number",
            field=models.CharField(
                db_index=True, unique=True, verbose_name="Enrolment Number"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="project_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="students",
                to="project.projectgroup",
                verbose_name="Project Group",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("student", "Student"), ("faculty", "Faculty")],
                default="student",
                verbose_name="User Role",
            ),
        ),
    ]
