# Generated by Django 4.2.1 on 2023-05-08 12:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_alter_student_department_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="faculty",
            options={"verbose_name": "Faculty", "verbose_name_plural": "Faculties"},
        ),
        migrations.AlterModelOptions(
            name="student",
            options={"verbose_name": "Student", "verbose_name_plural": "Students"},
        ),
        migrations.AlterField(
            model_name="faculty",
            name="department",
            field=models.CharField(
                choices=[
                    ("information_technology", "Information Technology"),
                    ("computer_science", "Computer Science"),
                    ("electronics", "Electronics and Telecommunication"),
                    ("electrical", "Electrical"),
                    ("mechanical", "Mechanical"),
                    ("civil", "Civil"),
                ],
                verbose_name="Department",
            ),
        ),
    ]
