# Generated by Django 4.2.1 on 2023-05-09 03:37

import core.db.fields
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("taggit", "0005_auto_20220424_2025"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created On"),
                ),
                (
                    "updated_on",
                    models.DateTimeField(auto_now=True, verbose_name="Updated On"),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("formation", "Formation"),
                            ("conformed", "Conformed"),
                        ],
                        default="formation",
                        verbose_name="Status",
                    ),
                ),
                (
                    "conformed_on",
                    models.DateField(
                        blank=True, null=True, verbose_name="Conformed On"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProjectGroupInvite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created On"),
                ),
                (
                    "updated_on",
                    models.DateTimeField(auto_now=True, verbose_name="Updated On"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        verbose_name="Status",
                    ),
                ),
                (
                    "expires_on",
                    models.DateTimeField(blank=True, verbose_name="Expires On"),
                ),
            ],
            options={
                "verbose_name": "Project Group Invite",
                "verbose_name_plural": "Project Group Invites",
            },
        ),
        migrations.CreateModel(
            name="ProjectIdea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created On"),
                ),
                (
                    "updated_on",
                    models.DateTimeField(auto_now=True, verbose_name="Updated On"),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                ("report_content", models.TextField(verbose_name="Report Content")),
                ("abstract_content", models.TextField(verbose_name="Abstract Content")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("completed", "Completed"),
                            ("rejected", "Rejected"),
                        ],
                        default="new",
                        verbose_name="Status",
                    ),
                ),
                (
                    "approved_on",
                    models.DateField(blank=True, null=True, verbose_name="Approved On"),
                ),
                (
                    "completed_on",
                    models.DateField(
                        blank=True, null=True, verbose_name="Completed On"
                    ),
                ),
                (
                    "uniqueness",
                    core.db.fields.PercentField(default=0, verbose_name="uniqueness"),
                ),
                (
                    "project_group",
                    models.ForeignKey(
                        limit_choices_to={"role": "faculty"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ideas",
                        to="project.projectgroup",
                        verbose_name="Project Idea",
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        help_text="A comma-separated list of tags.",
                        through="taggit.TaggedItem",
                        to="taggit.Tag",
                        verbose_name="Tags",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
