# Generated by Django 4.2.1 on 2023-05-09 03:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("user", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ProjectGroupInvite",
            name="created_by",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_invites",
                to="user.student",
            ),
        ),
        migrations.AddField(
            model_name="ProjectGroupInvite",
            name="project_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invites",
                to="project.projectgroup",
            ),
        ),
        migrations.AddField(
            model_name="ProjectGroupInvite",
            name="student",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invites",
                to="user.student",
            ),
        ),
        migrations.AddField(
            model_name="projectgroup",
            name="conformed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="conformed_student_groups",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="projectgroup",
            name="created_by",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_student_groups",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="projectgroup",
            name="faculty",
            field=models.ForeignKey(
                limit_choices_to={"role": "faculty"},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="project_groups",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="ProjectGroupInvite",
            unique_together={("project_group", "student")},
        ),
    ]
