# Generated by Django 4.2.1 on 2023-05-08 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0004_alter_faculty_options_alter_student_options_and_more"),
        ("project", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectgroup",
            name="faculty",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="project_groups",
                to="user.faculty",
            ),
        ),
        migrations.CreateModel(
            name="ProjectGroupInvites",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created On"),
                ),
                (
                    "updated_on",
                    models.DateTimeField(auto_now=True, verbose_name="Updated On"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        verbose_name="Status",
                    ),
                ),
                (
                    "expires_on",
                    models.DateTimeField(blank=True, verbose_name="Expires On"),
                ),
                (
                    "created_by",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_invites",
                        to="user.student",
                    ),
                ),
                (
                    "project_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invites",
                        to="project.projectgroup",
                    ),
                ),
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invites",
                        to="user.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Group Invite",
                "verbose_name_plural": "Project Group Invites",
                "unique_together": {("project_group", "student")},
            },
        ),
    ]
