# Generated by Django 4.2.1 on 2023-05-10 05:01

import core.db.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("project", "0003_alter_projectgroupinvites_created_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectidea",
            name="submitted_on",
            field=models.DateField(
                blank=True, editable=False, null=True, verbose_name="Submitted On"
            ),
        ),
        migrations.AlterField(
            model_name="projectgroup",
            name="conformed_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="conformed_student_groups",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="projectgroup",
            name="conformed_on",
            field=models.DateField(
                blank=True, editable=False, null=True, verbose_name="Conformed On"
            ),
        ),
        migrations.AlterField(
            model_name="projectgroup",
            name="created_by",
            field=models.OneToOneField(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_student_groups",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="projectgroup",
            name="status",
            field=models.CharField(
                choices=[("formation", "Formation"), ("conformed", "Conformed")],
                default="formation",
                editable=False,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="projectidea",
            name="approved_on",
            field=models.DateField(
                blank=True, editable=False, null=True, verbose_name="Approved On"
            ),
        ),
        migrations.AlterField(
            model_name="projectidea",
            name="completed_on",
            field=models.DateField(
                blank=True, editable=False, null=True, verbose_name="Completed On"
            ),
        ),
        migrations.AlterField(
            model_name="projectidea",
            name="project_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ideas",
                to="project.projectgroup",
                verbose_name="Project Group",
            ),
        ),
        migrations.AlterField(
            model_name="projectidea",
            name="uniqueness",
            field=core.db.fields.PercentField(default=0, verbose_name="Uniqueness"),
        ),
    ]
