# Generated by Django 4.2.1 on 2023-05-08 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0004_alter_faculty_options_alter_student_options_and_more"),
        ("project", "0003_alter_projectgroup_faculty_projectgroupinvites"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectgroup",
            name="conformed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="conformed_student_groups",
                to="user.student",
            ),
        ),
    ]
