# Generated by Django 4.2.1 on 2023-05-13 04:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0004_projectidea_submitted_on_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectidea",
            name="approved_on",
            field=models.DateTimeField(
                blank=True, editable=False, null=True, verbose_name="Approved On"
            ),
        ),
        migrations.AlterField(
            model_name="projectidea",
            name="completed_on",
            field=models.DateTimeField(
                blank=True, editable=False, null=True, verbose_name="Completed On"
            ),
        ),
        migrations.AlterField(
            model_name="projectidea",
            name="submitted_on",
            field=models.DateTimeField(
                blank=True, editable=False, null=True, verbose_name="Submitted On"
            ),
        ),
    ]
